### ISSUE TITLE
Every Example Throws this build error

### ISSUE THREAD

**Issue by 20080** [sarxos/webcam-capture#531] opened 2017-03-16 04:53 UTC
```
run:
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:97)
	at application1.Application1.main(Application1.java:23)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
C:\Users\Suraj\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)
```

**Comment by sarxos** [comment] 2017-03-16 08:17
Hi, 

Solution for this very common issue caused by the fact that people are not adding required JARs into the classpath, is described here:

https://github.com/sarxos/webcam-capture/wiki/How-to-solve-java.lang.ClassNotFoundException:-org.slf4j.LoggerFactory

This is duplicate of https://github.com/sarxos/webcam-capture/issues/185, https://github.com/sarxos/webcam-capture/issues/378 and [other](https://github.com/sarxos/webcam-capture/issues?utf8=%E2%9C%93&q=NoClassDefFoundError%20org%2Fslf4j%2FLoggerFactory%20).

**Closed by sarxos** 2017-03-16 08:17 UTC
