### ISSUE TITLE
Cannot execute task, cannot start native grabber

### ISSUE THREAD

**Issue by sarxos** [sarxos/webcam-capture#94] opened 2013-05-10 19:19 UTC
Extracted from #81

---

There is a new problem. It still does not show an image and shows the following exception (Note: It detects correctly, how many webcams there are connected, that is if I plug in the USB cam, the 

``` java
Webcam.getWebcams(Long.MAX_VALUE, TimeUnit.MILLISECONDS) 
```

command returns a list with 1 item, if I unplug it no device is found.). Here is the stacktrace when trying to open the webcam using open(true)

``` plain
Exception in thread "Thread-26" com.github.sarxos.webcam.WebcamException: Cannot execute task
        at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:57)
        at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:120)
        at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:35)
        at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.open(WebcamOpenTask.java:20)
        at com.github.sarxos.webcam.Webcam.open(Webcam.java:177)
        at android.hardware.d.run(Unknown Source)
Caused by: com.github.sarxos.webcam.WebcamException: Cannot start native grabber!
        at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.open(WebcamDefaultDevice.java:223)
        at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.handle(WebcamOpenTask.java:38)
        at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:66)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by wasifmirza** [comment] 2015-01-16 19:14
Hi, im accessing total 6 cameras,

For 3 cameras it just worked fine,,,but when i am trying to access 6 camera 
it throws an exception
com.github.sarxos.webcam.WebcamException: Cannot execute task


Please assit

**Comment by sarxos** [comment] 2015-01-16 21:55
@wasifmirza, your USB controlled does not have enough bandwidth to stream data from all the webcams at once. It can be easily calculated. USB 2.0 = 60 MB/s, 640x480 RGB @ 25 FPS = 21 MB/s, so you can stream ~2 or 3 cameras at once.

**Comment by wasifmirza** [comment] 2015-01-17 17:38
Can you please provide me a solution for this.... I have extension box of usb slots. USB 2.0.
7 slots. Any kind of suggestion....because i am using it in my project and i need to access 6 camera. Please give me a solution.

Waiting for your response.
Regards

**Comment by sarxos** [comment] 2015-01-17 18:03
@wasifmirza there is no possibility to extend USB capacity. You can connect any number of extension boxes, but your USB controller on your motherboard is still the same - it has limited capacity (60 MB/s for USB 2.0, which is max for almost all UVC cameras) and cannot be changed up. 

You can try using GStreamer v0.10 with [gstreamer-driver](https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-drivers/driver-gstreamer) which should stream more (due to smaller format: 4 bytes for two pixels instead of 6), but this is still too low to stream from 6 cameras at once.

As a workaround you may try to:
* open two cameras at once, 
* take the pictures,
* close them, 
* then open the next two, 
* take pictures,
* close them, 
* etc.

But the above will be pretty slow, so if you need speed, this may not be sufficient for your application.

**Comment by wasifmirza** [comment] 2015-01-17 19:23
Thanks alot @sarxos  for the suggestion.

I am also facing 1 more problem. It is the extension box for usb.

Due to port com reorganization i am not able to open 2 camera on that box.

**Comment by wasifmirza** [comment] 2015-01-17 19:23
@sarxos  should i mail you the basic program i made ?

**Comment by wasifmirza** [comment] 2015-01-17 19:26
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.JFrame;
import java.awt.*;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;

public class Camera extends JFrame {

	
	 JFrame cam=new JFrame("Check Camera");
	 
	  //Webcam.getWebcams().get(0):
	 
	 
	  Webcam w1;
	  Webcam w2;
	  Webcam w3;
	  Webcam w4;
	  Webcam w5;
	  Webcam w6;
	  
	  WebcamPanel cam1;
	  WebcamPanel cam2;
	  WebcamPanel cam3;
	  WebcamPanel cam4;
	  WebcamPanel cam5;
	  WebcamPanel cam6;
	
	  
	  /* Setting of webcam view can be done in following resolutions only :
	   * QQVGA (176 , 144)
QVGA (320 x 240)
VGA (640 x 480)
	   */
	
public Camera()
{
	
	
	 w1=Webcam.getWebcams().get(0);
	 
	 w1.setViewSize(new Dimension(176 , 144)); // set size
	 
	 
	 w2=Webcam.getWebcams().get(1);
	 w2.setViewSize(new Dimension(176 , 144)); // set size
	
	 
	 w3=Webcam.getWebcams().get(2);
	 w3.setViewSize(new Dimension(176 , 144)); // set size
	 
	 
	 w4=Webcam.getWebcams().get(3);
	 w4.setViewSize(new Dimension(176 , 144)); // set size
	 
	   
	 w5=Webcam.getWebcams().get(2);
	 w5.setViewSize(new Dimension(176 , 144)); // set size
	 
	 
	 w6=Webcam.getWebcams().get(5);
	 w6.setViewSize(new Dimension(176 , 144)); // set size
	 
	
	 cam1=new WebcamPanel(w1);
	 
	 cam2=new WebcamPanel(w2);
	 
	 cam3=new WebcamPanel(w3);
	 
	 cam4=new WebcamPanel(w4);
	 
	 cam5=new WebcamPanel(w5);
	 
	 cam6=new WebcamPanel(w6);
	 
	 cam.setLayout(new FlowLayout());
	 cam.setSize(1224,1000);
	 
	 cam.add(cam1);
	 
	 cam.add(cam2);
	 
	 cam.add(cam3);
	 cam.add(cam4);
	 
	 cam.add(cam5);
	 
	 cam.add(cam6);
	 
	 cam.setVisible(true);
	 
	 //check image capture
 BufferedImage image = w1.getImage();
	 try {
		ImageIO.write(image, "jpg", new File("test.jpg"));
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	 
}
public void camera_close()
{
	w1.close();
	w2.close();
	
	w3.close();
	w4.close();
	
	w5.close();
	
	w6.close();

}
public void camera_open()
{
	w1.open();
	
	w2.open();
	
	w3.open();
	w4.open();
	
	w5.open();
	
	w6.open();
	
}



}

**Comment by wasifmirza** [comment] 2015-01-17 19:27
This code can work with 4 cameras smoothly with resolution of each as 640,480
It runs when i connect 4 cameras on my laptop USB slots.

But when i connect my cameras to extension box it cannot add it and gives exceptions.

**Comment by sarxos** [comment] 2015-01-17 19:45
@wasifmirza, there is no way to fix this in Webcam Capture API. The USB ports and whole communication is being done by your operating system. If you experience problems with the external USB hub (or extension box) this is because:
* Your operating system is not able to handle this hardware, or
* Your USB controller is not able to multiplex traffic from 4 cameras on a single USB port (as I described previously, due to the USB bandwidth limit - 4 x 21 MB/s = 84 MB/s, which is much higher than 60 MB/s), or
* The USB hub hardware is not able to work properly with your USB controller.

You may try to connect 3 hubs to your USB sloths and try to connect 2 cameras to each hub (this will give you 6 cameras). This may work but I never tried this approach, and honestly I cannot guarantee such solution to work.

**Comment by wasifmirza** [comment] 2015-01-17 19:51
Once again thanks.

Is there is any function from which we can input webcam by the usb id or any of it's USB controller feature.

**Comment by wasifmirza** [comment] 2015-01-17 19:53
I mean we use

Webcam.getWebcams.get( number such as 0 to n );

Cant we use some else for 
.get(number);

because while detecting from external box there it must detect it....! 
It is not detecting  from it. Only 1 camera is detected.
And i got your answer that over bandwidth cant be used but now i want to know another to access the webcam using some class or id of usb.

**Comment by wasifmirza** [comment] 2015-01-17 19:56
And i am using windows 8 ... So there is no option of port in my device manager....!
If that would have been possible so i would have changed the port number...! but unfortunately i dont have the port option.

**Comment by sarxos** [comment] 2015-01-17 20:15
@wasifmirza, the Webcam Capture API does not operate on the USB level. The number you are passing to ```Webcam.getWebcams().get(..)``` is a camera identifier, not the port. The API is using operating system features to list and access webcams without dealing too much with the USB. At the very bottom level the camera is accessed (thru Microsoft API) with the URI like:

```plain
vfw:Microsoft WDM Image Capture (Win32):0
```

Where ```0``` in the above example is the first camera detected (by the operating system). However, it can be connected to USB1, USB2, or even to USB10 on USB hub, so as you can see there is no way to deal with the USB port itself.

**Comment by wasifmirza** [comment] 2015-01-17 20:19
@sarxos Yup i got you and thanks for the response for every single query...
Your work on webcam is appreciable and i liked it.

Thanks !

**Comment by wasifmirza** [comment] 2015-01-18 10:02
@sarxos  what if i use usb 3.0 . I have lappy with usb 3.0
and what if i use extension box with 3.0 
It will work?

**Comment by sarxos** [comment] 2015-01-18 10:49
@wasifmirza I guess this should be OK, but if and only if your camera is 3.0 compliant. In case it's 2.0 and your USB port is 3.0, the whole communication is still limited to 2.0 speed.

**Comment by wasifmirza** [comment] 2015-02-23 18:52
Hellos @sarxos  I have 1 issue. 

I am coding in Java using eclipse IDE. I have an start and stop button.
On start button and starting the loop of capturing of camera but when i am trying to close the window or to code on stop, the process doesnt break or that loop goes on taking pictures.

Can you please suggest me how to break or stop the camera on Frame close or to stop the camera between the process.

Thanks!

**Comment by sarxos** [comment] 2015-02-23 19:00
@wasifmirza, can you please prepare small code example to demonstrate your issue? Normally it should be enough to call ```close()``` on webcam to stop.

**Comment by wasifmirza** [comment] 2015-02-24 04:52
@sarxos  I have tried close() function also. But it doesnt work when the camera is capturing the images.

**Comment by sarxos** [comment] 2015-02-24 09:27
@wasifmirza, can you verify which threads are blocking?

**Comment by sarxos** [comment] 2015-02-24 10:04
@wasifmirza, I was testing the code below and I do not observe more than 1.5s delay between the window close and program end (which is actually expected because application must properly dispose the webcam in shutdown hooks).

```java
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import javax.swing.JFrame;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;


public class WebcamPanelExample {

	public static void main(String[] args) throws InterruptedException {

		final Webcam webcam = Webcam.getDefault();
		webcam.setViewSize(WebcamResolution.VGA.getSize());

		final WebcamPanel panel = new WebcamPanel(webcam);
		panel.setFPSDisplayed(true);
		panel.setDisplayDebugInfo(true);
		panel.setImageSizeDisplayed(true);
		panel.setMirrored(true);

		final JFrame window = new JFrame("Test webcam panel");
		window.addWindowListener(new WindowListener() {

			@Override
			public void windowClosed(WindowEvent e) {
				webcam.close();
				window.dispose();
			}

			@Override
			public void windowOpened(WindowEvent e) { }
			@Override
			public void windowIconified(WindowEvent e) { }
			@Override
			public void windowDeiconified(WindowEvent e) { }
			@Override
			public void windowDeactivated(WindowEvent e) { }
			@Override
			public void windowClosing(WindowEvent e) { }
			@Override
			public void windowActivated(WindowEvent e) { }
		});

		window.add(panel);
		window.setResizable(true);
		window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		window.pack();
		window.setVisible(true);
	}
}
```

I cannot do anything more in regards to this issue. You first need to figure out which thread is blocking your application. The only way to stop camera taking pictures is to ```close()``` it.

**Comment by salmansaifi7** [comment] 2018-09-13 17:54
I am also facing same issue.. but in some weird pattern..

Here is my application pattern:

1. this issue come whenever i am installing for the very first time, application is up, but not able to call webcam.open(); for fixing it we do restart (dirty shutdown) our application.
2. After step-1, This issue again come-back after OS (RHEL-7) restart, process came up via init.d scripts, it start failing while webcam.open(); now again we hv to restart..

Is there any fix/workaround available for this? should we try changing the default driver?

**Comment by salmansaifi7** [comment] 2018-09-13 18:52
this is the log when it fail:

_2018-09-13 11:41:10.0049 PDT  (webcam-discovery-service) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver - Found device USB 2.0 Camera /dev/video0
2018-09-13 11:41:10.0062 PDT  (ForkJoinPool.commonPool-worker-1) [DEBUG]: com.github.sarxos.webcam.Webcam - Setting new resolution 1280x720
2018-09-13 11:41:10.0066 PDT  (ForkJoinPool.commonPool-worker-1) [DEBUG]: com.github.sarxos.webcam.WebcamLock - Lock Webcam USB 2.0 Camera /dev/video0
2018-09-13 11:41:10.0071 PDT  (atomic-processor-1) [INFO]: com.github.sarxos.webcam.ds.cgt.WebcamOpenTask - Opening webcam USB 2.0 Camera /dev/video0
2018-09-13 11:41:10.0072 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Opening webcam device USB 2.0 Camera /dev/video0
2018-09-13 11:41:10.0073 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Webcam device /dev/video0 starting session, size java.awt.Dimen
sion[width=1280,height=720]
2018-09-13 11:41:10.0764 PDT  (ForkJoinPool.commonPool-worker-1) [DEBUG]: com.github.sarxos.webcam.WebcamLock - Unlock Webcam USB 2.0 Camera /dev/video0
2018-09-13 11:41:10.0766 PDT  (webcam-lock-[USB 2.0 Camera /dev/video0]) [DEBUG]: com.github.sarxos.webcam.WebcamLock - Lock updater has been interrupted
2018-09-13 11:41:10.0766 PDT  (ForkJoinPool.commonPool-worker-1) [DEBUG]: com.github.sarxos.webcam.Webcam - Webcam exception when opening
com.github.sarxos.webcam.WebcamException: Cannot execute task
        at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.open(WebcamOpenTask.java:20) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.Webcam.open(Webcam.java:295) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.Webcam.open(Webcam.java:250) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.Webcam.open(Webcam.java:236) ~[Sarxos_webcam-capture-0.x.jar:?]
       

        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_91]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_91]
Caused by: com.github.sarxos.webcam.WebcamException: Cannot start native grabber!
        at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.open(WebcamDefaultDevice.java:334) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.handle(WebcamOpenTask.java:38) ~[Sarxos_webcam-capture-0.x.jar:?]
        at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81) ~[Sarxos_webcam-capture-0.x.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]


_






and this is the log when it pass:


2018-09-13 11:33:20.0171 PDT  (ForkJoinPool.commonPool-worker-3) [DEBUG]: com.github.sarxos.webcam.WebcamLock - Lock Webcam USB 2.0 Camera /dev/video0
2018-09-13 11:33:20.0175 PDT  (atomic-processor-1) [INFO]: com.github.sarxos.webcam.ds.cgt.WebcamOpenTask - Opening webcam USB 2.0 Camera /dev/video0
2018-09-13 11:33:20.0175 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Opening webcam device USB 2.0 Camera /dev/video0
2018-09-13 11:33:20.0176 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Webcam device /dev/video0 starting session, size java.awt.Dimen
sion[width=1280,height=720]

2018-09-13 11:33:20.0913 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Webcam device session started
2018-09-13 11:33:20.0914 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Clear memory buffer
2018-09-13 11:33:21.0118 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Webcam device com.github.sarxos.webcam.ds.buildin.WebcamDefault
Device@540994ce is now open
2018-09-13 11:33:21.0119 PDT  (ForkJoinPool.commonPool-worker-3) [DEBUG]: com.github.sarxos.webcam.Webcam - Webcam is now open USB 2.0 Camera /dev/video0
2018-09-13 11:33:21.0152 PDT  (ForkJoinPool.commonPool-worker-3) [INFO]: com.hardware.device.camera.ImageCameraDeviceImpl - Image is clicked!
2018-09-13 11:33:21.0152 PDT  (ForkJoinPool.commonPool-worker-3) [DEBUG]: com.github.sarxos.webcam.Webcam - Closing webcam USB 2.0 Camera /dev/video0
2018-09-13 11:33:21.0181 PDT  (atomic-processor-1) [INFO]: com.github.sarxos.webcam.ds.cgt.WebcamCloseTask - Closing USB 2.0 Camera /dev/video0
2018-09-13 11:33:21.0181 PDT  (atomic-processor-1) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - Closing webcam device
2018-09-13 11:33:21.0366 PDT  (ForkJoinPool.commonPool-worker-3) [DEBUG]: com.github.sarxos.webcam.WebcamLock - Unlock Webcam USB 2.0 Camera /dev/video0
2018-09-13 11:33:21.0367 PDT  (webcam-lock-[USB 2.0 Camera /dev/video0]) [DEBUG]: com.github.sarxos.webcam.WebcamLock - Lock updater has been interrupted
2018-09-13 11:33:21.0368 PDT  (ForkJoinPool.commonPool-worker-3) [DEBUG]: com.github.sarxos.webcam.Webcam - Webcam USB 2.0 Camera /dev/video0 has been closed
2018-09-13 11:33:21.0505 PDT  (ForkJoinPool.commonPool-worker-3) [INFO]: com.hardware.device.camera.ImageCameraDeviceImpl - Image is saved to filesystem!
2018-09-13 11:33:21.0525 PDT  (ForkJoinPool.commonPool-worker-3) [INFO]: com.hardware.device.camera.ImageCameraDeviceImpl - Total time taken to click and process image: 1343 
millisec.
2018-09-13 11:33:22.0941 PDT  (webcam-discovery-service) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver - Searching devices
2018-09-13 11:33:22.0945 PDT  (webcam-discovery-service) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver - Found device USB 2.0 Camera /dev/video0
2018-09-13 11:33:25.0945 PDT  (webcam-discovery-service) [DEBUG]: com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver - Searching devices

**Closed** 2021-05-31 08:32 UTC
Labels: other
