### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by hemeshwari** [sarxos/webcam-capture#733] opened 2019-08-03 07:14 UTC
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:97)
        at DetectWebcamExample.main(DetectWebcamExample.java:7)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

**Comment by tirz** [comment] 2019-08-09 00:39
Duplicate of #732

**Comment by sarxos** [comment] 2021-01-29 13:16
See https://github.com/sarxos/webcam-capture/wiki/java.lang.ClassNotFoundException%3A-org.slf4j.LoggerFactory

**Closed by sarxos** 2021-01-29 13:16 UTC
